-- Write SQL queries to perform the following tasks using the Sakila database:
USE sakila;
-- 1. List the number of films per category.
SELECT c.name, COUNT(fc.film_id)
FROM category AS c
LEFT JOIN film_category AS fc
ON c.category_id = fc.category_id
GROUP BY c.name;

-- 2. Retrieve the store ID, city, and country for each store.
SELECT s.store_id, c.city, co.country
FROM store AS s
LEFT JOIN address AS a
ON a.address_id = s.address_id
LEFT JOIN city AS c
ON c.city_id = a.city_id
LEFT JOIN country AS co
ON co.country_id = c.country_id;

-- 3. Calculate the total revenue generated by each store in dollars.
SELECT s.store_id, SUM(p.amount) AS total_revenue_USD
FROM store AS s
LEFT JOIN staff AS st
ON s.store_id = st.store_id
LEFT JOIN payment AS p
ON st.staff_id = p.staff_id
GROUP BY s.store_id;


-- 4. Determine the average running time of films for each category.
SELECT c.name AS category_name, 
	   ROUND(AVG(f.length),2) AS average_running_time
FROM category AS c
LEFT JOIN film_category AS fc
ON c.category_id = fc.category_id
LEFT JOIN film as f
ON f.film_id = fc.film_id
GROUP BY c.name;

-- 5. Identify the film categories with the longest average running time.
SELECT c.name AS category_name, 
	   ROUND(AVG(f.length),2) AS average_running_time
FROM category AS c
LEFT JOIN film_category AS fc
ON c.category_id = fc.category_id
LEFT JOIN film as f
ON f.film_id = fc.film_id
GROUP BY c.name
ORDER BY average_running_time DESC;

-- 6. Display the top 10 most frequently rented movies in descending order.
SELECT title, COUNT(rental_id) AS times_rented
FROM film AS f
LEFT JOIN inventory AS i
ON f.film_id = i.film_id
LEFT JOIN rental AS r
ON r.inventory_id = i.inventory_id
GROUP BY f.title
ORDER BY times_rented DESC
LIMIT 10;

-- 7. Determine if "Academy Dinosaur" can be rented from Store 1.
SELECT f.title, i.store_id
FROM film AS f
LEFT JOIN inventory AS i
ON f.film_id = i.film_id
WHERE f.title = "Academy Dinosaur"
AND store_id = 1;

-- taking into account if rented or not

SELECT f.title, i.store_id
FROM film AS f
LEFT JOIN inventory AS i
ON f.film_id = i.film_id
LEFT JOIN rental AS r 
ON i.inventory_id = r.inventory_id 
WHERE f.title = "Academy Dinosaur" 
AND r.return_date IS NULL;


-- 8. Provide a list of all distinct film titles, along with their availability status in the inventory. 
-- Include a column indicating whether each title is 'Available' or 'NOT available.' 
-- Note that there are 42 titles that are not in the inventory, and this information can be obtained using 
-- a CASE statement combined with IFNULL."

SELECT f.title, 
				CASE
					WHEN MAX(
                    CASE
						WHEN IFNULL(i.inventory_id, 0)=0
						THEN 0
						ELSE 1
					END)=1
                    THEN "Available"
                    ELSE "NOT Available"
				END AS availability_status
FROM film AS f
LEFT JOIN inventory AS i
ON f.film_id = i.film_id
GROUP BY f.title;



